# Generated by Django 3.1.2 on 2020-10-17 18:47

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0007_recurringuserplan_card_masked_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='attributes',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
